server:
  port: 9008

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: MProject-user
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.248.31:3306/MP_user?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: MySQL
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    host: 47.106.248.31

  rabbitmq:
    host: 47.106.248.31

  thymeleaf:
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    check-template: true
    cache: false
#    mode: LEGACYHTML5
#    cache: false

jwt:
  config:
    key: user
    expire: 3600000
  mvc:
    static-path-pattern: /**
    view:
      suffix: .html
      prefix: /
  resources:
    static-locations: classpath:/resources/,
      classpath:/resources/,
      classpath:/static/,
      classpath:/public/,
      classpath:/itstyle