server:
  port: 9004

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: MProject-article
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.248.31:3306/MP_article?characterEncoding=utf-8
    username: root
    password: root

  jpa:
      database: MySQL
      show-sql: true
      generate-ddl: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
      host: 47.106.248.31
      port: 6379
#server:
#  port: 9004
#
#spring:
#  application:
#    name: project_article
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.2.129:3306/myproject_article?characterEncoding=utf-8
#    username: root
#    password: root123
#  jpa:
#    database: MySQL
#    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  redis:
#    host: 192.168.2.129
#    port: 6379

