server:
  port: 9006

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: MProject-comment
  data:
    mongodb:
      host: 47.106.248.31
      database: MP_comment

  redis:
      host: 47.106.248.31
      port: 6379

