server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: MProject-manager

zuul:
  routes:
    MProject-active:
      path: /active/**  #请求的规则（给请求增加了前缀）
      serviceId:  MProject-active #Eureka中服务的id值
    MProject-article:
      path: /article/**  #请求的规则（给请求增加了前缀）
      serviceId:  MProject-article #Eureka中服务的id值
      MProject-base:
        path: /base/**  #请求的规则（给请求增加了前缀）
        serviceId:  MProject-base #Eureka中服务的id值
      MProject-comments:
        path: /comment/**  #请求的规则（给请求增加了前缀）
        serviceId:  MProject-comment #Eureka中服务的id值
      MProject-elasticsearch:
        path: /elasticsearch/**  #请求的规则（给请求增加了前缀）
        serviceId:  MProject-elasticsearch #Eureka中服务的id值
      MProject-friend:
        path: /friend/**  #请求的规则（给请求增加了前缀）
        serviceId:  MProject-friend #Eureka中服务的id值
      MProject-qa:
        path: /qa/**  #请求的规则（给请求增加了前缀）
        serviceId:  MProject-qa #Eureka中服务的id值
      MProject-recruit:
        path: /recruit/**  #请求的规则（给请求增加了前缀）
        serviceId:  MProject-recruit #Eureka中服务的id值
      MProject-sms:
        path: /sms/**  #请求的规则（给请求增加了前缀）
        serviceId:  MProject-sms #Eureka中服务的id值
      MProject-user:
        path: /user/**  #请求的规则（给请求增加了前缀）
        serviceId:  MProject-user #Eureka中服务的id值
